Allow specifying whether local or all snapshots are shown by default
kopia/htmlui pull request #186
Opened 2023-09-11 14:27 UTC by PhracturedBlue

When I connect to the server http page, I prefer to see all snapshots shown by default.  every time I switch away and come back I need to reselect 'All' instead of 'Local'.  This just makes the default a preference option

2023-09-12 19:18 UTC, PhracturedBlue commented
I put this comment in the kopia PR, but I'll add it here too as any changes are probably more relevant here:
I noticed that this will result in a configuration setting that has no effect when using the kopiaUI application (since multiUser is false there).

Solutions:

keep the code as is
leave the setting always available and place it in a 'multi user' section
query multi-user mode on the preferences page and hide the config option
remove the config option altogether and default to 'All Snapshots' if there is no local snapshot
The last option cold be done entirely in the UI without a need for any server-side changes, but it is the least flexible.

2023-09-12 19:23 UTC, lupusA requested changes
Hi @PhracturedBlue, @jkowalski, 

i've tested this pr. Basically its working.

I've just got a question. Is it possible to store the selectedOwner instead of a boolean? As of now, we need to override the selectedOwner if it is null - based on the boolean that has been set by the user or using the default (true-> all snapshots, false-> local snapshots). 

Saving the specific selection seems more intuitive, as the old selection will be set every time we open the snapshot tab. 

What do you think?

Cheers,

2023-09-12 19:23 UTC, lupusA commented on src/PreferencesView.jsx
This looks good to me.

2023-09-12 19:23 UTC, lupusA commented on src/SourcesTable.jsx
Hi @PhracturedBlue,

there is a lint error in line 222:3. Can you fix it? Additionally, there is console log within the code that should be removed. 

Right now we need to override the selectedOwner in the rendering function, which basically throws the above mentioned lint error. For the first rendering, the state is not changed. The second rendering cycle then uses the set selectedOwner. 

Can we fix this?

2023-09-12 19:23 UTC, lupusA commented on src/contexts/UIPreferencesContext.tsx
We should extend the interface **SerializedUIPreferences** to reflect the new attribute **defaultSnapshotViewAll**.

2023-09-12 20:06 UTC, PhracturedBlue commented
I considered allowing selection of any user instead of just the all or local.  It didn't make sense to me to save this setting, since normally I'm just using it as a filter, and not as a permanent setting.  Whereas the 'Local' setting is of no use to me as I don't have any local snapshots.  It is also a little weird to me to use what is effectively a filter as a preference and store that on the server.  It would perhaps be better to store in in a local-store, but I don't see any enabling for that.  If we do go this way, it eliminates the need for altering the preferences screen, so maybe it is overall more inuitive.

Anyhow, I can store the value as a username.  we'll need to validate that the user exists each time, so I'm not sure it will actually simplify the code any though.

Please confirm you prefer preserving the last-selection, and I'll make the changes.  Looks like @jkowalski already merged the boolean parameter, so we'll need a new pull-requrst into kopia for this change.

2023-09-12 20:27 UTC, lupusA commented
Hi @PhracturedBlue, 

then we should just fix the code and implement it as it is - with the current logic. What you you think @jkowalski?

Cheers,

2023-09-12 20:59 UTC, PhracturedBlue commented
One further option I thought of:
We can remove the preferences config and update defaultSnapshotViewAll based on the last seen of set('latest', 'all').  I.e. it wouldn't store that last selected user, but it would store the last selected latest or all.

That has the benefit of not requiring a server-only configuration section in the preferences.

2023-09-13 03:31 UTC, PhracturedBlue commented
I ended up removing the configuration option, as the more I thought about it the less it seemed helpful.

2023-09-13 17:15 UTC, lupusA approved these changes
The changes look good to me. The selector now saves the last state - all or local snaphots.

Cheers

2023-09-13 17:15 UTC, lupusA commented on src/contexts/UIPreferencesContext.tsx
LGTM

2023-09-13 17:15 UTC, lupusA commented on src/SourcesTable.jsx
LGTM

2023-09-14 05:48 UTC, merged